// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Web.DataAccess.Data;

#nullable disable

namespace Web.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410195635_uuuuu")]
    partial class uuuuu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Web.Domain.Models.BookingOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConferenceSettingsId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceSettingsId");

                    b.ToTable("BookingOptions");
                });

            modelBuilder.Entity("Web.Domain.Models.Conference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Conferences");
                });

            modelBuilder.Entity("Web.Domain.Models.ConferenceEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConferenceSettingsId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceSettingsId");

                    b.ToTable("ConferenceEntries");
                });

            modelBuilder.Entity("Web.Domain.Models.ConferenceSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConferenceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceId")
                        .IsUnique();

                    b.ToTable("ConferenceSettings");
                });

            modelBuilder.Entity("Web.Domain.Models.FileManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FileStatus")
                        .HasColumnType("integer");

                    b.Property<int>("FileType")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.ToTable("FileManagers");
                });

            modelBuilder.Entity("Web.Domain.Models.FoodOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConferenceSettingsId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FoodOptionsType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceSettingsId");

                    b.ToTable("FoodOptions");
                });

            modelBuilder.Entity("Web.Domain.Models.ImportantDates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConferenceSettingsId")
                        .HasColumnType("integer");

                    b.Property<int>("ImportantDatesStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("NormalDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("UpdatedDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceSettingsId");

                    b.ToTable("ImportantDates");
                });

            modelBuilder.Entity("Web.Domain.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Affiliation")
                        .HasColumnType("text");

                    b.Property<int?>("ConferenceEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("ConferenceId")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsPresenting")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsStudent")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceEntryId");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("UserId", "ConferenceId")
                        .IsUnique()
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Web.Domain.Models.ProgramDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConferenceSettingsId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceSettingsId");

                    b.ToTable("ProgramDays");
                });

            modelBuilder.Entity("Web.Domain.Models.ProgramItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Chair")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("ProgramDayId")
                        .HasColumnType("integer");

                    b.Property<string>("Speaker")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProgramDayId");

                    b.ToTable("ProgramItems");
                });

            modelBuilder.Entity("Web.Domain.Models.ProgramPresentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("ProgramSessionId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProgramSessionId");

                    b.ToTable("ProgramPresentations");
                });

            modelBuilder.Entity("Web.Domain.Models.ProgramSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Chair")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("ProgramItemId")
                        .HasColumnType("integer");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProgramItemId");

                    b.ToTable("ProgramSessions");
                });

            modelBuilder.Entity("Web.Domain.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConferenceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPresenting")
                        .HasColumnType("boolean");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer");

                    b.Property<string>("SubmissionIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceId");

                    b.HasIndex("ParticipantId")
                        .IsUnique();

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Web.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Web.Domain.Models.BookingOptions", b =>
                {
                    b.HasOne("Web.Domain.Models.ConferenceSettings", "ConferenceSettings")
                        .WithMany("BookingOptions")
                        .HasForeignKey("ConferenceSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConferenceSettings");
                });

            modelBuilder.Entity("Web.Domain.Models.ConferenceEntry", b =>
                {
                    b.HasOne("Web.Domain.Models.ConferenceSettings", "ConferenceSettings")
                        .WithMany("ConferenceEntries")
                        .HasForeignKey("ConferenceSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConferenceSettings");
                });

            modelBuilder.Entity("Web.Domain.Models.ConferenceSettings", b =>
                {
                    b.HasOne("Web.Domain.Models.Conference", "Conference")
                        .WithOne("Settings")
                        .HasForeignKey("Web.Domain.Models.ConferenceSettings", "ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conference");
                });

            modelBuilder.Entity("Web.Domain.Models.FileManager", b =>
                {
                    b.HasOne("Web.Domain.Models.Participant", "Participant")
                        .WithMany("FileManagers")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Web.Domain.Models.FoodOptions", b =>
                {
                    b.HasOne("Web.Domain.Models.ConferenceSettings", "ConferenceSettings")
                        .WithMany("FoodOptions")
                        .HasForeignKey("ConferenceSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConferenceSettings");
                });

            modelBuilder.Entity("Web.Domain.Models.ImportantDates", b =>
                {
                    b.HasOne("Web.Domain.Models.ConferenceSettings", "ConferenceSettings")
                        .WithMany("ImportantDates")
                        .HasForeignKey("ConferenceSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConferenceSettings");
                });

            modelBuilder.Entity("Web.Domain.Models.Participant", b =>
                {
                    b.HasOne("Web.Domain.Models.ConferenceEntry", "ConferenceEntry")
                        .WithMany()
                        .HasForeignKey("ConferenceEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Web.Domain.Models.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Conference");

                    b.Navigation("ConferenceEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web.Domain.Models.ProgramDay", b =>
                {
                    b.HasOne("Web.Domain.Models.ConferenceSettings", "ConferenceSettings")
                        .WithMany("ProgramDays")
                        .HasForeignKey("ConferenceSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConferenceSettings");
                });

            modelBuilder.Entity("Web.Domain.Models.ProgramItem", b =>
                {
                    b.HasOne("Web.Domain.Models.ProgramDay", "ProgramDay")
                        .WithMany("ProgramItems")
                        .HasForeignKey("ProgramDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramDay");
                });

            modelBuilder.Entity("Web.Domain.Models.ProgramPresentation", b =>
                {
                    b.HasOne("Web.Domain.Models.ProgramSession", "ProgramSession")
                        .WithMany("ProgramPresentations")
                        .HasForeignKey("ProgramSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramSession");
                });

            modelBuilder.Entity("Web.Domain.Models.ProgramSession", b =>
                {
                    b.HasOne("Web.Domain.Models.ProgramItem", "ProgramItem")
                        .WithMany("ProgramSessions")
                        .HasForeignKey("ProgramItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramItem");
                });

            modelBuilder.Entity("Web.Domain.Models.Submission", b =>
                {
                    b.HasOne("Web.Domain.Models.Conference", "Conference")
                        .WithMany()
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Domain.Models.Participant", "Participant")
                        .WithOne()
                        .HasForeignKey("Web.Domain.Models.Submission", "ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conference");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("Web.Domain.Models.Conference", b =>
                {
                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Web.Domain.Models.ConferenceSettings", b =>
                {
                    b.Navigation("BookingOptions");

                    b.Navigation("ConferenceEntries");

                    b.Navigation("FoodOptions");

                    b.Navigation("ImportantDates");

                    b.Navigation("ProgramDays");
                });

            modelBuilder.Entity("Web.Domain.Models.Participant", b =>
                {
                    b.Navigation("FileManagers");
                });

            modelBuilder.Entity("Web.Domain.Models.ProgramDay", b =>
                {
                    b.Navigation("ProgramItems");
                });

            modelBuilder.Entity("Web.Domain.Models.ProgramItem", b =>
                {
                    b.Navigation("ProgramSessions");
                });

            modelBuilder.Entity("Web.Domain.Models.ProgramSession", b =>
                {
                    b.Navigation("ProgramPresentations");
                });
#pragma warning restore 612, 618
        }
    }
}
