<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Context\**" />
      <EmbeddedResource Remove="Context\**" />
      <None Remove="Context\**" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Web.Domain\Web.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Laraue.EfCoreTriggers.Common" Version="10.4.0" />
        <PackageReference Include="Laraue.EfCoreTriggers.PostgreSql" Version="10.4.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.2" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Repositories\" />
    </ItemGroup>
    
</Project>
